plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7' apply false
	id 'io.spring.dependency-management' version '1.1.7' apply false
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

allprojects {
    group = 'com.example'
    version = '0.0.1-SNAPSHOT'
}


subprojects {
    apply plugin: 'java'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }

    repositories {
        mavenCentral()
    }

    if (project.name != "config-service") {
        dependencies {
            /*lombok*/
            compileOnly 'org.projectlombok:lombok'
            annotationProcessor 'org.projectlombok:lombok'

            /*devtools*/
            developmentOnly 'org.springframework.boot:spring-boot-devtools'

            testImplementation 'org.springframework.boot:spring-boot-starter-test'
            testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
        }
    }

    tasks.named('test') {
        useJUnitPlatform()
    }
}

// Eureka Server와 Gateway를 제외한 나머지에만 Web 추가
configure(subprojects.findAll {
    it.name != 'apigateway-service' && it.name != 'service-discovery'
}) {
    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-web'
    }
}